import { useState } from "react";
import { useParams, Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Send, Download, ArrowLeft, FileText, FileDown } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { supabase } from "@/integrations/supabase/client";

interface Message {
  role: "user" | "assistant";
  content: string;
}

const Chat = () => {
  const { stageId } = useParams();
  const { toast } = useToast();
  const [messages, setMessages] = useState<Message[]>([
    {
      role: "assistant",
      content: "Hi! I'm your CPF assistant. Ask me anything about CPF schemes, contributions, or how they apply to your situation. I'll explain everything in simple terms.",
    },
  ]);
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  const stageTitles: Record<string, string> = {
    "fresh-graduate": "Fresh Graduate",
    "early-career": "Early Career",
    "homebuyer": "First-Time Homebuyer",
    "married": "Getting Married",
    "parent": "New Parent",
    "mid-career": "Mid-Career",
  };

  const handleSend = async () => {
    if (!input.trim() || isLoading) return;

    const userMessage: Message = { role: "user", content: input };
    setMessages((prev) => [...prev, userMessage]);
    setInput("");
    setIsLoading(true);

    // Simulate AI response - this will be replaced with actual RAG implementation
    setTimeout(() => {
      const assistantMessage: Message = {
        role: "assistant",
        content: "I understand your question about CPF. Let me explain... (This is a demo response. Connect Lovable AI to enable real CPF assistance.)",
      };
      setMessages((prev) => [...prev, assistantMessage]);
      setIsLoading(false);
    }, 1000);
  };

  const handleExportFull = () => {
    const stageTitle = stageTitles[stageId || ""] || "CPF Chat";
    const timestamp = new Date().toISOString().split('T')[0];
    const fileName = `${stageTitle.replace(/\s+/g, '-')}_${timestamp}.json`;
    
    const exportData = {
      stage: stageTitle,
      exportDate: new Date().toISOString(),
      messages: messages,
      messageCount: messages.length,
    };

    const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    toast({
      title: "Conversation Exported",
      description: "Full conversation downloaded successfully.",
    });
  };

  const handleExportSummary = async () => {
    if (messages.length <= 1) {
      toast({
        title: "No Conversation",
        description: "Start a conversation before exporting a summary.",
        variant: "destructive",
      });
      return;
    }

    setIsExporting(true);
    try {
      const { data, error } = await supabase.functions.invoke('summarize-conversation', {
        body: { messages },
      });

      if (error) throw error;

      const stageTitle = stageTitles[stageId || ""] || "CPF Chat";
      const timestamp = new Date().toISOString().split('T')[0];
      const fileName = `${stageTitle.replace(/\s+/g, '-')}_Summary_${timestamp}.txt`;

      const summaryContent = `CPF Consultation Summary
Stage: ${stageTitle}
Date: ${new Date().toLocaleDateString()}
Messages: ${messages.length}

${data.summary}

---
Generated by CPF Assistant
`;

      const blob = new Blob([summaryContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = fileName;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast({
        title: "Summary Generated",
        description: "Conversation summary downloaded successfully.",
      });
    } catch (error) {
      console.error('Export summary error:', error);
      toast({
        title: "Export Failed",
        description: "Failed to generate conversation summary.",
        variant: "destructive",
      });
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="flex h-screen flex-col bg-gradient-to-b from-background to-secondary/20">
      {/* Header */}
      <div className="border-b bg-card/50 backdrop-blur-sm">
        <div className="container mx-auto flex items-center justify-between px-4 py-4">
          <div className="flex items-center gap-4">
            <Link to="/stages">
              <Button variant="ghost" size="icon">
                <ArrowLeft className="h-5 w-5" />
              </Button>
            </Link>
            <div>
              <h1 className="text-xl font-semibold text-foreground">
                {stageTitles[stageId || ""] || "CPF Assistant"}
              </h1>
              <p className="text-sm text-muted-foreground">Ask me anything about CPF</p>
            </div>
          </div>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline" className="gap-2" disabled={isExporting}>
                <Download className="h-4 w-4" />
                {isExporting ? "Generating..." : "Export Chat"}
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem onClick={handleExportFull}>
                <FileDown className="mr-2 h-4 w-4" />
                Full Conversation (JSON)
              </DropdownMenuItem>
              <DropdownMenuItem onClick={handleExportSummary} disabled={isExporting}>
                <FileText className="mr-2 h-4 w-4" />
                AI Summary (Text)
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </div>

      {/* Chat Messages */}
      <ScrollArea className="flex-1 px-4 py-6">
        <div className="container mx-auto max-w-3xl space-y-4">
          {messages.map((message, index) => (
            <div
              key={index}
              className={`flex ${message.role === "user" ? "justify-end" : "justify-start"}`}
            >
              <Card
                className={`max-w-[80%] ${
                  message.role === "user"
                    ? "bg-primary text-primary-foreground"
                    : "bg-card"
                }`}
              >
                <div className="p-4">
                  <p className="whitespace-pre-wrap">{message.content}</p>
                </div>
              </Card>
            </div>
          ))}
          {isLoading && (
            <div className="flex justify-start">
              <Card className="bg-card">
                <div className="p-4">
                  <div className="flex gap-2">
                    <div className="h-2 w-2 animate-bounce rounded-full bg-primary [animation-delay:-0.3s]"></div>
                    <div className="h-2 w-2 animate-bounce rounded-full bg-primary [animation-delay:-0.15s]"></div>
                    <div className="h-2 w-2 animate-bounce rounded-full bg-primary"></div>
                  </div>
                </div>
              </Card>
            </div>
          )}
        </div>
      </ScrollArea>

      {/* Input Area */}
      <div className="border-t bg-card/50 backdrop-blur-sm">
        <div className="container mx-auto max-w-3xl px-4 py-4">
          <div className="flex gap-2">
            <Input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyPress={(e) => e.key === "Enter" && handleSend()}
              placeholder="Ask about CPF contributions, housing schemes, retirement planning..."
              className="flex-1"
              disabled={isLoading}
            />
            <Button onClick={handleSend} disabled={isLoading || !input.trim()} className="gap-2">
              <Send className="h-4 w-4" />
              Send
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Chat;
